version: "2"

services:
  streamlit:
    image: test1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - "./data:/app/data"
      - "./project:/app/project"
